name: social_logins
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    


# dependancies
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  floating_bottom_navigation_bar: ^1.5.2
  simple_floating_bottom_nav_bar: ^0.0.3
  calendar_date_picker2: ^0.5.3
  http: ^1.2.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  firebase_analytics: ^10.8.5
  google_mobile_ads: ^4.0.0
  firebase_messaging: ^14.7.15
  flutter_stripe: ^10.0.0
  flutter_dotenv: ^5.1.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  tap_debouncer: ^2.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"


flutter:

  uses-material-design: true
  fonts:
      - family: NoirPro
        fonts: 
          - asset: fonts/Noir_regular.otf
          - asset: fonts/Noir_medium.otf
  
  assets:
    - assets/.env

