// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQlQkOstAPkFeoibEZgBEY-oTd8xldrE',
    appId: '1:23436470153:web:d67b7299b8aca5b511e358',
    messagingSenderId: '23436470153',
    projectId: 'bookingapp-7775b',
    authDomain: 'bookingapp-7775b.firebaseapp.com',
    storageBucket: 'bookingapp-7775b.appspot.com',
    measurementId: 'G-ZLYWMYW32Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8p4_znglPPK8VlpCCgxogigqEgafjXq8',
    appId: '1:23436470153:android:d19a917330c4cb6911e358',
    messagingSenderId: '23436470153',
    projectId: 'bookingapp-7775b',
    storageBucket: 'bookingapp-7775b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaNCwszZoSpdNBdkp6a93fbhLtYIANH-w',
    appId: '1:23436470153:ios:203c4e0733a7e51111e358',
    messagingSenderId: '23436470153',
    projectId: 'bookingapp-7775b',
    storageBucket: 'bookingapp-7775b.appspot.com',
    iosBundleId: 'com.example.socialLogins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaNCwszZoSpdNBdkp6a93fbhLtYIANH-w',
    appId: '1:23436470153:ios:52bdcef352bd1f5d11e358',
    messagingSenderId: '23436470153',
    projectId: 'bookingapp-7775b',
    storageBucket: 'bookingapp-7775b.appspot.com',
    iosBundleId: 'com.example.socialLogins.RunnerTests',
  );
}
